[colors]

[colors.normal]
black = "#2c2525"
red = "#fd6c85"
green = "#adda78"
yellow = "#f9cc6c"
blue = "#85dacc"
magenta = "#a8a9eb"
cyan = "#85dacc"
white = "#e6d9db"

[colors.bright]
black = "#72696a"
red = "#fd6c85"
green = "#adda78"
yellow = "#f9cc6c"
blue = "#85dacc"
magenta = "#a8a9eb"
cyan = "#85dacc"
white = "#fff1f3"

[colors.cursor]
cursor = '#c3b7b8'
text = '#c3b7b8'

[colors.primary]
background = '#2c2525'
foreground = '#e6d9db'

[colors.selection]
background = '#403e41'
text = '#e6d9db'
